Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CodingTest.Controllers
{
    public class AjaxController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Data()
        {
            return PartialView();
        }
    }
}

Controllers/FizzBuzzController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CodingTest.Controllers
{
    public class FizzBuzzController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/LinqController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CodingTest.Models;
using Microsoft.AspNetCore.Mvc;

namespace CodingTest.Controllers
{
    public class LinqController : Controller
    {
        public IActionResult Index()
        {
            StudentGradeReportViewModel studentGradeReport = new StudentGradeReportViewModel();

            //*Average Grade Percentage for Class
            studentGradeReport.AverageGrade = GetAverageGrade();

            //* How many students received each letter grade
            studentGradeReport.LetterGradeCounts = GetLetterGradeCounts();

            //* A list of students ordered by their number grade descending(Grade - FirstName LastName)
            studentGradeReport.GradeList = GetGradeListDescending();

            return View(studentGradeReport);
        }

        private decimal GetAverageGrade()
        {
            decimal averageGrade;

            averageGrade = (decimal)(from a in GradeList
                            select a.NumberGrade).Average();

            return averageGrade;
        }

        private List<GradeCount> GetLetterGradeCounts()
        {
            List<GradeCount> gradeCounts = (from g in GradeList
                                            group g by g.LetterGrade into letterGrades
                                            orderby letterGrades.Key
                                            select new GradeCount {
                                                LetterGrade = letterGrades.Key,
                                                LetterGradeCount = letterGrades.Count()
                                            }).ToList();

            return gradeCounts;
        }

        private List<StudentGrade> GetGradeListDescending()
        {
            List<StudentGrade> gradeList = (from g in GradeList
                                            orderby g.NumberGrade descending
                                            select g).ToList();
            return gradeList;
        }

        public static List<StudentGrade> GradeList = new List<StudentGrade>
        {
            new StudentGrade { FirstName="Rosina", LastName="Pickel", NumberGrade=92, LetterGrade="A" },
            new StudentGrade { FirstName="Valene", LastName="Belvin", NumberGrade=75, LetterGrade="C" },
            new StudentGrade { FirstName="Floria", LastName="Dambrosia", NumberGrade=86, LetterGrade="B" },
            new StudentGrade { FirstName="Lindsay", LastName="Slade", NumberGrade=95, LetterGrade="A" },
            new StudentGrade { FirstName="Tia", LastName="Sabat", NumberGrade=86, LetterGrade="B" },
            new StudentGrade { FirstName="Shaunta", LastName="Milani", NumberGrade=88, LetterGrade="B" },
            new StudentGrade { FirstName="Billye", LastName="Bose", NumberGrade=82, LetterGrade="B" },
            new StudentGrade { FirstName="Elvera", LastName="Ayres", NumberGrade=81, LetterGrade="B" },
            new StudentGrade { FirstName="Migdalia", LastName="Rouse", NumberGrade=76, LetterGrade="C" },
            new StudentGrade { FirstName="Kelsie", LastName="Mccord", NumberGrade=83, LetterGrade="B" },
            new StudentGrade { FirstName="Shaquita", LastName="Blackledge", NumberGrade=83, LetterGrade="B" },
            new StudentGrade { FirstName="Kaitlin", LastName="Wurst", NumberGrade=96, LetterGrade="A" },
            new StudentGrade { FirstName="Lacy", LastName="Minear", NumberGrade=76, LetterGrade="C" },
            new StudentGrade { FirstName="Lashaunda", LastName="Raskin", NumberGrade=90, LetterGrade="A" },
            new StudentGrade { FirstName="Bethanie", LastName="Mastronardi", NumberGrade=96, LetterGrade="A" },
            new StudentGrade { FirstName="Joesph", LastName="Peavy", NumberGrade=81, LetterGrade="B" },
            new StudentGrade { FirstName="Fransisca", LastName="Scherr", NumberGrade=66, LetterGrade="D" },
            new StudentGrade { FirstName="Yer", LastName="Schoonover", NumberGrade=90, LetterGrade="A" },
            new StudentGrade { FirstName="Jean", LastName="Monzon", NumberGrade=95, LetterGrade="A" },
            new StudentGrade { FirstName="Elena", LastName="Fickel", NumberGrade=85, LetterGrade="B" },
            new StudentGrade { FirstName="Lynell", LastName="Mcnally", NumberGrade=65, LetterGrade="D" },
            new StudentGrade { FirstName="Leslee", LastName="Babin", NumberGrade=79, LetterGrade="C" },
            new StudentGrade { FirstName="Layne", LastName="Cobler", NumberGrade=79, LetterGrade="C" },
            new StudentGrade { FirstName="Zada", LastName="Dingee", NumberGrade=93, LetterGrade="A" },
            new StudentGrade { FirstName="Ricky", LastName="Vaughan", NumberGrade=79, LetterGrade="C" },
            new StudentGrade { FirstName="Ardella", LastName="Bellah", NumberGrade=75, LetterGrade="C" },
            new StudentGrade { FirstName="Rozella", LastName="Netherland", NumberGrade=68, LetterGrade="D" },
            new StudentGrade { FirstName="Shandra", LastName="Ridley", NumberGrade=79, LetterGrade="C" },
            new StudentGrade { FirstName="Franklyn", LastName="Hoback", NumberGrade=73, LetterGrade="C" },
            new StudentGrade { FirstName="Rufus", LastName="Coblentz", NumberGrade=82, LetterGrade="B"}
        };
    }
}

Controllers/RecursionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CodingTest.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text;

namespace CodingTest.Controllers
{
    public class RecursionController : Controller
    {
        public IActionResult Index()
        {
            StringBuilder builder = new StringBuilder();
            ViewData["locations"] = Recurse(LocationList, builder);

            return View();
        }

        private static string Recurse(Location location, StringBuilder builder, int spacer = 0)
        {
            builder.AppendLine("<div class=space" + spacer + ">" + location.Name + "</div>");

            if (location.ChildrenLocations.Count > 0)
            {
                spacer++;
                for (int i = 0; i < location.ChildrenLocations.Count; i++)
                {
                    Recurse(location.ChildrenLocations[i], builder, spacer);
                }
                spacer--;
            }

            return builder.ToString();
        }

        private static Location LocationList = new Location
        {
            Name = "Americas",
            ChildrenLocations = new List<Location>{
                new Location
                {
                    Name = "North America",
                    ChildrenLocations = new List<Location>
                    {
                        new Location
                        {
                            Name = "United States",
                            ChildrenLocations = new List<Location>
                            {
                                new Location {Name="Illinois"},
                                new Location {Name="Iowa"},
                                new Location {Name="New York"},
                                new Location {Name="Texas"},
                                new Location {Name="West Virginia"},
                                new Location {Name="Utah"},
                                new Location {Name="Vermont"},
                                new Location {Name="Kansas"},
                                new Location {Name="Washington"},
                                new Location {Name="Indiana"},
                                new Location {Name="Wisconsin"},
                                new Location {Name="California"},
                                new Location {Name="Arizona"},
                                new Location {Name="Colorado"},
                                new Location {Name="Montana"},
                                new Location {Name="Arkansas"},
                                new Location {Name="Tennessee"},
                                new Location {Name="New Jersey"},
                                new Location {Name="New Mexico"},
                                new Location {Name="Virginia"},
                                new Location {Name="Connecticut"},
                                new Location {Name="Kentucky"},
                                new Location {Name="Maryland"},
                                new Location {Name="Massachusetts"},
                                new Location {Name="Louisiana"},
                                new Location {Name="Maine"},
                                new Location {Name="Nebraska"},
                                new Location {Name="Nevada"},
                                new Location {Name="Alabama"},
                                new Location {Name="Hawaii"},
                                new Location {Name="North Dakota"},
                                new Location {Name="Ohio"},
                                new Location {Name="Idaho"},
                                new Location {Name="South Dakota"},
                                new Location {Name="Wyoming"},
                                new Location {Name="Alaska"},
                                new Location {Name="Delaware"},
                                new Location {Name="Michigan"},
                                new Location {Name="Minnesota"},
                                new Location {Name="Florida"},
                                new Location {Name="Georgia"},
                                new Location {Name="New Hampshire"},
                                new Location {Name="North Carolina"},
                                new Location {Name="Oklahoma"},
                                new Location {Name="Oregon"},
                                new Location {Name="Pennsylvania"},
                                new Location {Name="Rhode Island"},
                                new Location {Name="South Carolina"},
                                new Location {Name="Mississippi"},
                                new Location {Name="Missouri"}
                            }
                        },
                        new Location
                        {
                            Name = "Canada",
                            ChildrenLocations = new List<Location>
                            {
                                new Location {Name="Quebec"},
                                new Location {Name="British Columbia"},
                                new Location {Name="Saskatchewan"},
                                new Location {Name="New Brunswick"},
                                new Location {Name="Alberta"},
                                new Location {Name="Newfoundland and Labrador"},
                                new Location {Name="Manitoba"},
                                new Location {Name="Nova Scotia"},
                                new Location {Name="Prince Edward Island"},
                                new Location {Name="Ontario"}

                            }
                        }
                    }
                },
                new Location
                {
                    Name = "Central America",
                    ChildrenLocations = new List<Location>
                    {
                        new Location {Name="Honduras"},
                        new Location {Name="El Salvador"},
                        new Location {Name="Costa Rica"},
                        new Location {Name="Panama"},
                        new Location {Name="Guatemala"},
                        new Location {Name="Belize"},
                        new Location {Name="Nicaragua"}
                    }
                },
                new Location
                {
                    Name = "South America",
                    ChildrenLocations = new List<Location>
                    {
                        new Location {Name="Bouvet Island"},
                        new Location {Name="Paraguay"},
                        new Location {Name="Colombia"},
                        new Location {Name="Brazil"},
                        new Location {Name="Argentina"},
                        new Location {Name="Venezuela"},
                        new Location {Name="French Guiana"},
                        new Location {Name="Guyana"},
                        new Location {Name="South Georgia and the South Sandwich Islands"},
                        new Location {Name="Bolivia"},
                        new Location {Name="Peru"},
                        new Location {Name="Uruguay"},
                        new Location {Name="Suriname"},
                        new Location {Name="Ecuador"},
                        new Location {Name="Chile"},
                        new Location {Name="Falkland Islands"}
                    }
                }
            }
        };
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CodingTest</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CodingTest</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FizzBuzz" asp-action="Index">FizzBuzz</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Linq" asp-action="Index">LINQ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ajax" asp-action="Index">Ajax</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Recursion" asp-action="Index">Recursion</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - CodingTest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>